apiVersion: v1
kind: Service
metadata:
  name: cc-storage
  namespace: caen-camp
spec:
  selector:
    app.kubernetes.io/name: cc-storage
  ports:
    - name: http
      port: 3000
      targetPort: 3000
