apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cc-api
  namespace: caen-camp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: cc.lab.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cc-api
                port:
                  number: 3000
