apiVersion: v1
kind: Service
metadata:
  name: cc-api
  namespace: caen-camp
spec:
  selector:
    app.kubernetes.io/name: cc-api
    app.kubernetes.io/instance: cc-api-prod
    app.kubernetes.io/version: 1.0.0
  ports:
    - name: http
      port: 3000
      targetPort: 3000
