apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cc-tld
  namespace: caen-camp
spec:
  secretName: cc-tld-cert
  dnsNames:
    - "cc.lab.ovh"
  issuerRef:
    name: acme
    kind: ClusterIssuer
