apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-api
  namespace: caen-camp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cc-api
      app.kubernetes.io/instance: cc-api-prod
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cc-api
        app.kubernetes.io/instance: cc-api-prod
        app.kubernetes.io/version: 1.0.0
    spec:
      terminationGracePeriodSeconds: 2
      containers:
        - name: api-server
          imagePullPolicy: Always
          image: ghcr.io/mxvincent/k8s-caen-camp:1.0.0
          ports:
            - name: http
              containerPort: 3000


