apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-staging
  namespace: cert-manager
spec:
  acme:
    email: max.cavalor@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-staging
    solvers:
      - http01:
          ingress:
            class: nginx
