apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-api
  namespace: caen-camp
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: cc-api
      app.kubernetes.io/instance: cc-api-prod
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cc-api
        app.kubernetes.io/instance: cc-api-prod
        app.kubernetes.io/version: 1.0.0
    spec:
      terminationGracePeriodSeconds: 2
      containers:
        - name: api-server
          livenessProbe:
            timeoutSeconds: 1
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 2
            httpGet:
              path: /
              port: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          imagePullPolicy: Always
          image: ghcr.io/mxvincent/k8s-caen-camp:1.0.0
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: HTTP_PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: cc-env


